//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDoanhThu
    {
        public string MaBC { get; set; }
        public string MaHoaDon { get; set; }
    
        public virtual Mon_Ban Mon_Ban { get; set; }
    }
}
