//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mon_Ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mon_Ban()
        {
            this.BaoCaoDoanhThus = new HashSet<BaoCaoDoanhThu>();
        }
    
        public int MaBan { get; set; }
        public int MaMon { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaHoaDon { get; set; }
        public string MaNV { get; set; }
    
        public virtual Ban Ban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoCaoDoanhThu> BaoCaoDoanhThus { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
